// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoS0qr9i4h8PCWed-ZFDSCdSDEfjgU6CU',
    appId: '1:621358222594:web:ac6e57cda3863f29eb061b',
    messagingSenderId: '621358222594',
    projectId: 'project-3d099',
    authDomain: 'project-3d099.firebaseapp.com',
    storageBucket: 'project-3d099.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbugyhGsygJAcXwPbZzV9f6VqXMkzdjI',
    appId: '1:621358222594:android:2d02434accf136f5eb061b',
    messagingSenderId: '621358222594',
    projectId: 'project-3d099',
    storageBucket: 'project-3d099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPP1d-crobwhVHtPWnvkQwmNXeCtN6hDk',
    appId: '1:621358222594:ios:60f5014837813f81eb061b',
    messagingSenderId: '621358222594',
    projectId: 'project-3d099',
    storageBucket: 'project-3d099.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPP1d-crobwhVHtPWnvkQwmNXeCtN6hDk',
    appId: '1:621358222594:ios:60f5014837813f81eb061b',
    messagingSenderId: '621358222594',
    projectId: 'project-3d099',
    storageBucket: 'project-3d099.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoS0qr9i4h8PCWed-ZFDSCdSDEfjgU6CU',
    appId: '1:621358222594:web:9a4a26f1a87e6680eb061b',
    messagingSenderId: '621358222594',
    projectId: 'project-3d099',
    authDomain: 'project-3d099.firebaseapp.com',
    storageBucket: 'project-3d099.firebasestorage.app',
  );
}
